### ISSUE TITLE
Integrate a usage statistics mechanism

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#111]
To get an idea about how many people are actually using the site, we need to collect some sort of metrics. The requirements are:

1. **privacy-preserving**: we only need to know the number of visitors, which routes they look at, whether they use a phone or a desktop.
2. **public**: the statistics must be available to the public.

**Comment by strdr4605** [comment]
We can use Spitbee for now, then if traffic increase we can switch to Plausible, and maybe  request **free tier**. Also can we request payment from RTEC?

**Comment by iamandrewluca** [comment]
I can integrate Splitbee for now. And in case we go past 2.5K events/month I can take payment responsibility on me for some time.

we should open a Roata Wăy Patreon account 🙂
