### ISSUE TITLE
On-the-fly vehicle off-route updates

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#118]
Sometimes a vehicle can be taken off a route (e.g., if there's a defect), the map has to be updated accordingly - the vehicle should be hidden. The API has just been extended to provide such notifications in real-time:  https://github.com/roataway/api-documentation#eventroute

Summary of how it works:
- Subscribe to `event.route.<upstream route id>` (e.g. `event.route.52` for route with upstream_id=52, defined here https://github.com/roataway/infrastructure-data/blob/develop/routes.csv)
- Payloads will be a JSON: `{"event": "remove", "rtu_id": "0000115", "board": "2186"}`

The example above shows that vehicle with tracker ID `0000115`, assigned to board `2186` was removed from the route that has the id `52`.

Currently there's an undocumented attribute in the payload:  `"new_route_id": 1` - it shows the ID of the new route the vehicle has been re-assigned to. However, note that sometimes a vehicle can be taken offline for good - so this parameter will be absent. Whether it needs to be there or now - the subject is open for discussion.

Hiding the vehicle: ideally, we hide it with a "fade out" effect, to signalize to users that it didn't just vanish like a fart in the wind. The best UX for this is also an open matter.

**Comment by strdr4605** [comment]
Will try to work on it

**Comment by iamandrewluca** [comment]
Ok, but take a break first :)

**Comment by strdr4605** [comment]
@iamandrewluca I am in between jobs 😄
