### ISSUE TITLE
Render vehicles as "off" if they're within trolleybus parks

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#120]
Sometimes a vehicle returns to the park (e.g., because of some run-time defects) but it remains linked to a certain route, so views like this can happen:
![image](https://user-images.githubusercontent.com/48152696/83332028-31f42000-a299-11ea-8618-5185f1c74e62.png)

A discussion with RTEC made it clear that these events are rather frequent and they cannot guarantee that they'll always "unmap" it from a route when this happens.

A good idea might be to render vehicles that are within the boundary of the "park" as gray, or semi-transparent, with a label that says "În mentenanță" - so as to make it clear to users that this vehicle is not a part of the game. This is especially critical if you're waiting for a trolleybus late at night and you see a blue dot on a map, off-route... but it gives you false hopes.

So, we should render these dots in a separate way. The suggested alternative style is:
- 30% opacity
- gray colour
- "Under maintenance" tooltip shown when the marker is clicked.

Chișinău has 3 parks:
![image](https://user-images.githubusercontent.com/48152696/83331963-04a77200-a299-11ea-8e81-f56a608e9ec6.png)

![image](https://user-images.githubusercontent.com/48152696/83332245-556b9a80-a29a-11ea-8cc6-6d80d1a005b8.png)

![image](https://user-images.githubusercontent.com/48152696/83332262-70d6a580-a29a-11ea-9b74-d8e9d4a67b91.png)

So it seems that we need some sort of a geo-fencing feature. Note that the areas are irregular shapes - so the "fence" has to be an arbitrary polygon, not a rectangle.

**Comment by roata** [comment]
So, @iamandrewluca you were right, but the problem is slightly less tricky - the logic is "is it in the park?" rather than "is it off-route?" (which would be a bigger challenge, because route shapes are more complex).

**Comment by roata** [comment]
The contours:

Parcul#1, Buiucani
![image](https://user-images.githubusercontent.com/48152696/83332514-e3945080-a29b-11ea-9c5c-a959bfb32a69.png)

47.03782046385607, 28.81591558456421
47.035422117402916, 28.82065773010254
47.03597784141986, 28.82155895233154
47.037878958764374, 28.818544149398804

Parcul#2, Botanica
![image](https://user-images.githubusercontent.com/48152696/83332645-aaa8ab80-a29c-11ea-8677-2dd3ecab1cb8.png)

46.987505737947956, 28.88427972793579
46.98884505415609, 28.885556459426883
46.988479124097836, 28.886511325836178
46.98729349350121, 28.888131380081173
46.98627617221127, 28.886168003082272


Parcul#3, Ciocana
![image](https://user-images.githubusercontent.com/48152696/83332587-4980d800-a29c-11ea-8101-e3957e020a45.png)

47.02578377253985, 28.88381838798523
47.025578993676476, 28.887734413146973
47.029286832141274, 28.888195753097534
47.02950622279598, 28.88421535491943

**Comment by strdr4605** [comment]
Will take this issue and probably will submit a PR for Hacktoberfest.
