### ISSUE TITLE
Add feedback mechanism

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#130]
We need a way to allow non-expert users send bug-reports, feature requests (or praise :-). At the moment this is only doable via Github issues. 

However, the problem is that our user base consists mainly of non tech-savvy people, we can't expect them to be programmers, have a Github account, and so on.

Ideally, this is a low-friction mechanism that allows one to provide feedback without creating an account anywhere, or starting another program (e.g., an email client, a chat client, etc.).

**Comment by iamandrewluca** [comment]
https://docs.sentry.io/platforms/javascript/enriching-error-data/user-feedback/

**Comment by grigorebudac** [comment]
I'll take it.

**Comment by iamandrewluca** [comment]
Ok, thanks! :rocket:

**Comment by roata** [comment]
Having checked the suggestion made by @iamandrewluca, I want to point out that Sentry's form assumes you are sending a crash report.

They also have an option to customize the strings, I believe we have to leverage that in order to make it more generic. This way, when a user wants to provide some feedback that is not necessarily a crash or a bug report, they won't have to do this through a window titled "it looks like we're experiencing some internal issues".

**Comment by iamandrewluca** [comment]
Maybe exists other free solutions for user feedback?

**Comment by grigorebudac** [comment]
Maybe we can  get use of the github's api and write the feedback as an issue ? 
or, there are some open source projects for collection feedback and we can take one of them and run it inside heroku or something ([getfider](https://getfider.com/))

**Comment by iamandrewluca** [comment]
I think we want to keep the app as anonymous as possible.

@roata

**Comment by roata** [comment]
Indeed, it is an important concern. However, I think ťdt if we take the Sentry approach it is still acceptable: if someone wants to remain anonymous, they can fill out a bogus address (we can make it clear in the Form itself).

On the one hand we have to give people a way to do this, but on the other: we have to make sure they won't spam us to death.


Maybe we can just say "write an email to xxxxx" but in that case there is not much transparency - there's only one person accessing that email and that person will soon become the bottleneck.
