### ISSUE TITLE
Route labels taking too much space on mobile

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#132]
The introduction of #128 brought a minor inconvenience for mobile users - roughly 25% of the screen is now occupied by the list of selected routes.
![image](https://user-images.githubusercontent.com/48152696/93707992-27ed7a00-fb33-11ea-9a84-e9ffdd4509c2.png)

This can be resolved by adding a "collapse" button that might look like this:
![image](https://user-images.githubusercontent.com/48152696/93708097-d0034300-fb33-11ea-8b62-ed969e87baf3.png)

It will compress this widget into a more compact representation, which can be expanded back into its normal state:
![image](https://user-images.githubusercontent.com/48152696/93708174-69325980-fb34-11ea-839e-dfcb056e070d.png)

This functionality can be retained for the regular, desktop version too. In other words, this doesn't have to be a "mobile only" feature.

**Comment by viorelrj** [comment]
Hi. Is anybody on this issue now? Willing to try and make my first open-source contribution

**Comment by iamandrewluca** [comment]
Hi Viorel! Don't think anyone started to work on this. You can take it. Thanks! :rocket:

**Comment by viorelrj** [comment]
@iamandrewluca, upd: sorry, will actually have to pass this one.

**Comment by iamandrewluca** [comment]
No problems. 🙂

**Comment by roata** [comment]
@viorelrj, could you provide some more context? It would help us if we knew the rationale behind your decision, so we could adapt.

If the task is not clearly defined - we can make refine the description. Alternatively, if you just don't have the time - it is out of our control, but at least we know this is not because of obvious deficiencies in our requirements.

And just in case - if you're not confident you can implement this, we're here to provide mentoring. You can get guidance from top-notch engineers like Andrei, or from less bright [but still supportive] people like me.

**Comment by viorelrj** [comment]
@iamandrewluca, thanks for great reply! The reason is that it is only now that I noticed that this project might slightly be a subject of non-concurrency contract I signed at my current job, thus will have to stop the initiative. Thanks for understanding and offering to help.
