### ISSUE TITLE
Zoom in: unwanted marker drift

### ISSUE THREAD

**Issue by roata** [roataway/roataway-web#49]
When zooming in and out, sometimes the markers are drifting. See this GIF as a demo of the effect: https://media.giphy.com/media/YlSfDHaiixJS4LKDRq/giphy.gif

There was a related issue: https://github.com/roataway/web-ui/issues/33, with the suggestion to disable the `transform` style while a zoom in/out operation is in progress.

**Comment by iamandrewluca** [comment]
Notes:
* Combine transport markers and render them as geojson
