### ISSUE TITLE
The app is causing huge CPU usage

### ISSUE THREAD

**Issue by PlugaruT** [roataway/roataway-web#76]
Right now, if I open roataway.md on Firefox, my computer starts to feel like it want to lift-off. 
Here is a link to a recording I made.
https://send.firefox.com/download/16b8de6d4996248f/#3f7_dpQbchaDjxknqHF8KQ

PS: The password is the same you used to connect to the MQTT broker.

**Comment by iamandrewluca** [comment]
@PlugaruT I'll do some profiling.

**Comment by roata** [comment]
I can confirm that, some people started complaining about the same thing - I believe this happens because now there are more tracked trolleybuses. This is especially relevant on mobile platforms.

**Comment by iamandrewluca** [comment]
Notes:
* Combine station markers when selecting multiple routes
* Combine route segments when selecting multiple routes
